In [6]:
import numpy as np
a = np.array([1, 2, 3, 4, 5]) 
print(a)

b = np.array([[1, 2, 3], [4, 5, 6]]) 
print (b)

c = np.zeros((3, 4))
print(c)

d = np.ones((2,2))
print(d)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1.]
 [1. 1.]]


In [7]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=a+b
print(c)

d=np.array([[1,2],[3,4]])
e=np.array([[5,6],[7,8]])
f=d*e
print(f)

g=np.array([[1,2],[3,4]])
h=np.array([[5,6],[7,8]])
i=np.dot(g,h)
print(i)



[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
